### ISSUE TITLE
Obtener coordenadas de los eventos de Meetup

### ISSUE THREAD

**Issue by carlosfdev** [OSWeekends/eventpoints-backend#14]
Actualmente se está scrapeando la URL de google maps directamente, nos traemos el parámetro 'query' y de ahí sacamos la latitud y longitud.

El problema es que en query a veces no vienen solo las coordeandas sino que también puede venir directamente la dirección.

Hay que buscar alternativa, quizá podemos dar de alta un api key gratuita de Google Maps para consultar las coordenadas, o lo podemos scrapear de otra forma, o incluso podríamos lanzar a nuestro mapa la misma query que se lanza a Google Maps si no los permite, y ya que se encargue de pintar el marker a través de esa query.

**Comment by danielgj** [comment]
Already fixed
