### ISSUE TITLE
Translate documentation

### ISSUE THREAD

**Issue by danielgj** [OSWeekends/eventpoints-backend#42]
Current README is in Spanish only and can be translated to english.

**Comment by htmluke** [comment]
Hello! I can translate in English for you <3

**Comment by alaabouayed** [comment]
Happy to take this on if @htmluke doesn't

**Comment by alaabouayed** [comment]
I've created a PR for this issue. https://github.com/OSWeekends/eventpoints-backend/pull/46

**Comment by danielgj** [comment]
Already translated in its current version by @alaabouayed 
We'll keep this open as we are going to extend Spanish version

**Comment by JukMR** [comment]
Hi ! I would like to extend the readme translation with the new updates

**Comment by danielgj** [comment]
Hi @JukMR
There is a new spanish version much more updated.
It would be great if you can translate it and add in both a link to swich language so anyone can decide if read it in Spanish or English. If everything is OK I think it would be better if main version is english one.
Please remember to do the PR to/from dev branch.

**Comment by JukMR** [comment]
Perfect, I will do that so ! I hope to make a PR in a few hours. Also thank you for the _"to/from dev branch"_ tip.
